### ISSUE TITLE
Add simple todo list widget to the tasks list tab

### ISSUE THREAD

**Issue by octetful** [octetful/karmayoga-web#16]
### Problem Statement
Currently the tasks tab is an empty placeholder. The idea is to enable to users to quickly enter task items / todos through this tab. We need to add a simple todo list widget that allows the users to enter new tasks, view tasks, and mark tasks as done.

### Expected Outcomes
- [x] User is able to enter new tasks in the todo list on the tasks tab.
- [x] User is able to view entered tasks in the todo list on the tasks tab.
- [x] User is able to mark entered tasks as done in the todo list on the tasks tab.
